### ISSUE TITLE
not exists on maven central

### ISSUE THREAD

**Issue by hoat4** [m-abboud/FontVerter#21]
I couldn't find the artifact on Maven Central. This page shows no search results: https://search.maven.org/search?q=g:org.fontverter%20AND%20a:FontVerter%20AND%20v:1.2.22

The Spring Plugins repository seems to include the artifacts of this project, but only some old versions: https://repo.spring.io/plugins-release/org/fontverter/FontVerter/

**Comment by hoat4** [comment]
Found it at groupId "net.mabboud.fontverter". Please update the README, it shows `org.fontverter`.

**Comment by m-abboud** [comment]
fixed
