### ISSUE TITLE
Cannot detect name for fonts

### ISSUE THREAD

**Issue by ala85** [m-abboud/FontVerter#4]
I am trying to analyse fonts files (woff, otf and ttf) and extract metadata information such as font name. For instance, when analysing the attached file [JustAFileName.zip](https://github.com/m-abboud/FontVerter/files/1117751/JustAFileName.zip), the below code is not able to retrieve the font name information:

```
FVFont font = FontVerter.readFont(file);
String fontName = font.getName(); // always returns null
```

So far I have been unable to get the font name for any font I tried to analyse, so my guess is that either there is a bug or all the fonts I tried are somehow "corrupted".

**Comment by m-abboud** [comment]
awesome working on this now. Should be fixed by end of today

**Comment by m-abboud** [comment]
Fixed. Also added some new name getters to FontProperties (use font.getProperties()) including version, full name, weight and copyright notice

**Comment by ala85** [comment]
Thanks a lot! Will the fix be released on some repository with a new version (I assume 1.12.20)?
