### ISSUE TITLE
java.lang.NumberFormatException: Value out of range. Value:"11001010" Radix:2

### ISSUE THREAD

**Issue by dmitri-blinov** [m-abboud/FontVerter#6]
The following error is caught when converting font to WOFF2. 

> java.lang.NumberFormatException: Value out of range. Value:"11001010" Radix:2
> 	at java.lang.Byte.parseByte(Byte.java:151) ~[?:1.8.0_162]
> 	at org.mabb.fontverter.woff.WoffOutputStream.writeFlagByte(WoffOutputStream.java:67) ~[fontverter-1.2.20.jar:?]
> 	at org.mabb.fontverter.woff.Woff2Font$Woff2Table.getDirectoryData(Woff2Font.java:122) ~[fontverter-1.2.20.jar:?]
> 	at org.mabb.fontverter.woff.WoffFont.getTableDirectoryData(WoffFont.java:83) ~[fontverter-1.2.20.jar:?]
> 	at org.mabb.fontverter.woff.WoffFont.getRawData(WoffFont.java:74) ~[fontverter-1.2.20.jar:?]
> 	at org.mabb.fontverter.woff.Woff2Font.getRawData(Woff2Font.java:65) ~[fontverter-1.2.20.jar:?]
> 	at org.mabb.fontverter.woff.WoffHeader.calculateValues(WoffHeader.java:93) ~[fontverter-1.2.20.jar:?]
> 	at org.mabb.fontverter.woff.WoffFont.getData(WoffFont.java:58) ~[fontverter-1.2.20.jar:?]
> 

It seems to be an issue with unsigned byte parsing. By default all byte values are signed in java, so the method java.lang.Byte.parseByte can not be used.

**Comment by m-abboud** [comment]
Oops yeah aware bytes are signed in java probably forgot for this case. Haven't touched fontVerter in a couple months but will try fix when I get home from work in 8 hours.

**Comment by m-abboud** [comment]
Oh and could you upload the font your trying to convert here please?

**Comment by dmitri-blinov** [comment]
For now I can only tell the font is ms comic sans. See https://www.microsoft.com/Typography/Fonts/font.aspx?FMID=1920. If needed I could upload the file tomorrow morning, sorry.

**Comment by m-abboud** [comment]
Ok cool yeah I can grab that and test

**Comment by dmitri-blinov** [comment]
Here is the font file, have a look!
[comic.zip](https://github.com/m-abboud/FontVerter/files/1722930/comic.zip)

**Comment by m-abboud** [comment]
cool sorry for the delay, I fixed the unsigned byte convert issue issue but now it's running into an issue with arbitrary table tags so fixing that now..

**Comment by dmitri-blinov** [comment]
Well, it seems conversion to WOFF2 works, thanks for your efforts!

**Comment by m-abboud** [comment]
Oops you are correct. I just deployed 1.2.21 to maven central (won't show up in the search sites for a little though but if you just put in the new version number it will work)
